apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: cfax-portal
    app.kubernetes.io/component: back-end
  {{- with .Values.container }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cfax-portal
      app.kubernetes.io/component: back-end
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cfax-portal
        app.kubernetes.io/component: back-end
    spec:
      containers:
        - name: {{ $.Release.Name }}
          image: europe-central2-docker.pkg.dev/carfax-431019/cfax-back-end/cfax-{{ $.Release.Name }}:{{ $.Values.imageLabel }}
          ports:
            - containerPort: 50080
              name: {{ $.Values.containerPortName }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-env-vars-{{ include "help.configID" $ }}
          {{- if .pullPolicy }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          resources:
            requests:
              memory: {{ .requests.memory }}
              cpu: {{ .requests.cpu }}
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}
  {{- end }}