apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: cfax-portal
    app.kubernetes.io/component: front-end
  annotations:
    cloud.google.com/neg: '{"exposed_ports": { {{ .Values.containerPort | quote }}: {"name": "cfax-dev-{{ .Release.Name }}"}}}'
spec:
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app.kubernetes.io/name: cfax-portal
    app.kubernetes.io/component: front-end
  type: ClusterIP